### ISSUE TITLE
QAQC script - first steps

### ISSUE THREAD

**Issue by w-alanna** [w-alanna/COMPASS-sensor-data#1]
- [x] Step 1: read in sample data file and compute number of NAs and standard deviation (ignoring NAs) for each `research_name` into a summary data (data frame)
- [x] Step 2: do the above by day of year, i.e. so the summary output has `research_name`, `year`, `day`, `NA_count`, `sd` -- the `lubridate` package will likely be useful for this
- [ ] Generalize this: get list of files in `data/` and do the above for each of them (see [list.files](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/list.files)), combining the results into a single output

**Comment by bpbond** [comment]
Suggestion -- 
- Use readr::read_csv
- Create a new column with the date (not date time)
- Outside of the function, after calling it, graph the results using ggplot2!
