### ISSUE TITLE
Into July!

### ISSUE THREAD

**Issue by bpbond** [w-alanna/COMPASS-sensor-data#17]
- [x] Figure out where the `summarise` warnings are coming from -- shouldn't be returning more than one row
- [x] Figure out why some mad values are `NA`
- [ ] Try running Ryan's example given in #16  -- we want multiple nodes but not using the array approach. When that works, bring the slurm/sbatch settings into your scripts
- [x] Maybe when submitting a job, the script should clear out previous results? That way there's no confusion about what's newly generated or not

**Comment by w-alanna** [comment]
Some of the mad values are na because for some files, all the values for a certain research name are na
