### ISSUE TITLE
New Steps

### ISSUE THREAD

**Issue by w-alanna** [w-alanna/COMPASS-sensor-data#9]
- [x] Date column needs to be fixed
- [x] p_sd should be renamed for clarity
- [x] Find outliers using median absolute deviation
- [ ] @bpbond - readings on outliers
- [ ] Use SLURM ID to find folder instead of site and year

**Comment by bpbond** [comment]
@w-alanna You know, the Wikipedia article on outliers is good: https://en.wikipedia.org/wiki/Outlier
